[package]
name    = "rust-stb-image"
version = "0.1.0"
authors = [ "Mozilla Servo" ]

build   = "./configure && make"

[[lib]]
name       = "stb_image"
path       = "lib.rs"
crate_type = [ "dylib", "staticlib" ]